ARG PYTHON_BASE_IMAGE=python:3.12.13-alpine3.22
FROM ${PYTHON_BASE_IMAGE}

RUN addgroup -S sandbox -g 10001 \
    && adduser -S -D -H -G sandbox -u 10001 sandbox

WORKDIR /workspace
USER 10001:10001
ENTRYPOINT ["python"]
