apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agent-platform
resources:
  - namespace.yaml
  - identities.yaml
  - configuration.yaml
  - workloads.yaml
  - services.yaml
  - disruption-budgets.yaml
  - network-policies.yaml
  - autoscaling.yaml
  - prometheus-adapter-config.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: agent-platform
      app.kubernetes.io/managed-by: kustomize
